version: '3.0'

services:
  jupyter:
    image: vassiliskrikonis/pyviz
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/opt/notebooks
      - ./flinkcep/data:/opt/flinkcep-results
      - ./results:/opt/rtec-results
    command: jupyter notebook /opt/notebooks --ip=0.0.0.0 --allow-root --no-browser

  yap:
    build: ./rtec
    volumes:
      - ./results:/opt/results
